#ifndef __MAIN_H
#define __MAIN_H
#include "sys.h"
#include "led.h"
#include "delay.h"
#include "key.h"

#include "lcd.h"
#include "usart.h"
#include "24cxx.h"
#include "w25qxx.h"
#include "touch.h"
#include "fonthanzi.h"
#include "rs485.h"
#include "timer.h"
#include "beep.h"


#define SET_BUTTON_X_MIN_COORDINATE     (10)
#define SET_BUTTON_X_MAX_COORDINATE     (210)
#define SET_BUTTON_Y_MIN_COORDINATE     (680)
#define SET_BUTTON_Y_MAX_COORDINATE     (730)


#define OUT_BUTTON_X_MIN_COORDINATE     (150)
#define OUT_BUTTON_X_MAX_COORDINATE     (350)
#define OUT_BUTTON_Y_MIN_COORDINATE     (750)
#define OUT_BUTTON_Y_MAX_COORDINATE     (800)


#define JIAHAO_BUTTON_X_MIN_COORDINATE     (67)
#define JIAHAO_BUTTON_X_MAX_COORDINATE     (167)
#define JIAHAO_BUTTON_Y_MIN_COORDINATE     (472)
#define JIAHAO_BUTTON_Y_MAX_COORDINATE     (572)

#define JIANHAO_BUTTON_X_MIN_COORDINATE     (317)
#define JIANHAO_BUTTON_X_MAX_COORDINATE     (417)
#define JIANHAO_BUTTON_Y_MIN_COORDINATE     (472)
#define JIANHAO_BUTTON_Y_MAX_COORDINATE     (572)


#define WENDUSHANG_BUTTON_X_MIN_COORDINATE     (100)
#define WENDUSHANG_BUTTON_X_MAX_COORDINATE     (300)
#define WENDUSHANG_BUTTON_Y_MIN_COORDINATE     (120)
#define WENDUSHANG_BUTTON_Y_MAX_COORDINATE     (170)


#define WENDUXIA_BUTTON_X_MIN_COORDINATE     (300)
#define WENDUXIA_BUTTON_X_MAX_COORDINATE     (480)
#define WENDUXIA_BUTTON_Y_MIN_COORDINATE     (120)
#define WENDUXIA_BUTTON_Y_MAX_COORDINATE     (170)


#define SHIDUSHANG_BUTTON_X_MIN_COORDINATE     (100)
#define SHIDUSHANG_BUTTON_X_MAX_COORDINATE     (300)
#define SHIDUSHANG_BUTTON_Y_MIN_COORDINATE     (180)
#define SHIDUSHANG_BUTTON_Y_MAX_COORDINATE     (230)


#define SHIDUXIA_BUTTON_X_MIN_COORDINATE     (300)
#define SHIDUXIA_BUTTON_X_MAX_COORDINATE     (480)
#define SHIDUXIA_BUTTON_Y_MIN_COORDINATE     (180)
#define SHIDUXIA_BUTTON_Y_MAX_COORDINATE     (230)


#define GUANGZHAOSHANG_BUTTON_X_MIN_COORDINATE     (100)
#define GUANGZHAOSHANG_BUTTON_X_MAX_COORDINATE     (300)
#define GUANGZHAOSHANG_BUTTON_Y_MIN_COORDINATE     (240)
#define GUANGZHAOSHANG_BUTTON_Y_MAX_COORDINATE     (290)


#define GUANGZHAOXIA_BUTTON_X_MIN_COORDINATE     (300)
#define GUANGZHAOXIA_BUTTON_X_MAX_COORDINATE     (480)
#define GUANGZHAOXIA_BUTTON_Y_MIN_COORDINATE     (240)
#define GUANGZHAOXIA_BUTTON_Y_MAX_COORDINATE     (290)

#define FENGSUSHANG_BUTTON_X_MIN_COORDINATE     (100)
#define FENGSUSHANG_BUTTON_X_MAX_COORDINATE     (300)
#define FENGSUSHANG_BUTTON_Y_MIN_COORDINATE     (300)
#define FENGSUSHANG_BUTTON_Y_MAX_COORDINATE     (350)


#define FENGSUXIA_BUTTON_X_MIN_COORDINATE     (300)
#define FENGSUXIA_BUTTON_X_MAX_COORDINATE     (480)
#define FENGSUXIA_BUTTON_Y_MIN_COORDINATE     (300)
#define FENGSUXIA_BUTTON_Y_MAX_COORDINATE     (350)


#define ZAOSHENSHANG_BUTTON_X_MIN_COORDINATE     (100)
#define ZAOSHENSHANG_BUTTON_X_MAX_COORDINATE     (300)
#define ZAOSHENSHANG_BUTTON_Y_MIN_COORDINATE     (360)
#define ZAOSHENSHANG_BUTTON_Y_MAX_COORDINATE     (410)


#define ZAOSHENXIA_BUTTON_X_MIN_COORDINATE     (300)
#define ZAOSHENXIA_BUTTON_X_MAX_COORDINATE     (480)
#define ZAOSHENXIA_BUTTON_Y_MIN_COORDINATE     (360)
#define ZAOSHENXIA_BUTTON_Y_MAX_COORDINATE     (410)

#define CO2SHANG_BUTTON_X_MIN_COORDINATE     (100)
#define CO2SHANG_BUTTON_X_MAX_COORDINATE     (300)
#define CO2SHANG_BUTTON_Y_MIN_COORDINATE     (420)
#define CO2SHANG_BUTTON_Y_MAX_COORDINATE     (470)

#define CO2XIA_BUTTON_X_MIN_COORDINATE     (300)
#define CO2XIA_BUTTON_X_MAX_COORDINATE     (480)
#define CO2XIA_BUTTON_Y_MIN_COORDINATE     (420)
#define CO2XIA_BUTTON_Y_MAX_COORDINATE     (470)


#endif
